# Generated by Django 5.2.17 on 2026-08-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_tin', models.CharField(db_index=True, max_length=50)),
                ('payment_kind', models.CharField(db_index=True, max_length=20)),
                ('amount_etb', models.PositiveIntegerField()),
                ('payment_channel', models.CharField(max_length=64)),
                ('transaction_ref', models.CharField(max_length=128)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('quarter_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenants_tenantpaymentsubmission',
                'ordering': ['-submitted_at'],
                'managed': False,
            },
        ),
    ]
